rn=input("enter Roll no.:")
n=input("enter Student name.:")
h=int(input("enter hindi marks:"))
e=int(input("enter english marks:"))
s=int(input("enter science marks:"))
c=int(input("enter computer marks:"))
m=int(input("enter math's marks:"))
t=h+e+s+c+m
p=t/500*100
print("\n\n")
print("\t______________________________________")
print("\t\tReport Card")
print("\t______________________________________")
print()
print("\troll no.:\t",rn,"\t\tname:\t",n)
print()
print("\thindi:\t",h,"\t\tenglish:\t",e)
print()
print("\tcomputer:\t",c,"\t\ttotal:\t500")
print()
print("\tObain marks:",t,"\tpercentage:",p,"%")
print()
print("\t_________________________________________")
print("\t\t\tXYZ School")
print("\t_________________________________________")
